StudentGlossary.WebMVC/Models/WordViewModel.cs
using StudentGlossary.Entities;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace StudentGlossary.WebMVC.Models
{
    public class WordViewModel
    {
        public int WordId { get; set; }

        [Required]
        [StringLength(50, MinimumLength = 3)]
        public string Term { get; set; }

        [Required]
        [StringLength(2000, MinimumLength = 5)]
        public string Definition { get; set; }

        public DateTime CreatedAt { get; set; }

        public int GlossaryId { get; set; }
        public string GlossaryName { get; set; }
        public int GlossaryUserId { get; set; }

        public int UserId { get; set; }
        public string UserName { get; set; }

        public string CourseId { get; set; }
        public string CourseName { get; set; }
    }
}

StudentGlossary.WebMVC/Controllers/GlossaryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using StudentGlossary.Entities;
using StudentGlossary.Repositories;
using StudentGlossary.WebMVC.Models;

namespace StudentGlossary.WebMVC.Controllers
{
    public class GlossaryController : Controller
    {
        IUnitOfWork uof;
        public GlossaryController(IUnitOfWork uof)
        {
            this.uof = uof;
        }

        [Authorize(Roles = "admin")]
        public IActionResult Index()
        {
            List<GlossaryListingViewModel> list = new List<GlossaryListingViewModel>();
            uof.GlossaryRepository.GetAll().ToList().ForEach(c =>
            {
                GlossaryListingViewModel glossary = new GlossaryListingViewModel
                {
                    GlossaryId = c.GlossaryId,
                    Name = c.Name,
                    CourseId = c.CourseId,
                    CourseName = c.Course.Name,
                    UserName = c.User.Name
                };
                list.Add(glossary);
            });
            return View(list);
        }



        [HttpGet]
        [Authorize(Roles = "teacher, admin")]
        public IActionResult Accesses(int id)
        {
            Glossary glossary = uof.GlossaryRepository.GetSingle(id);
            if (glossary==null || glossary.UserId!= int.Parse(User.FindFirst(x => x.Type == "UserId").Value))
            {
                return NotFound();
            }

            GlossaryAccessesViewModel gavm = new GlossaryAccessesViewModel();
            gavm.GrantedUsers = new List<UserViewModel>();
            gavm.SearchedUsers = new List<UserViewModel>();

            
            gavm.Glossary = new GlossaryViewModel()
            {
                
                CourseId = glossary.CourseId,
                Description = glossary.Description,
                Name = glossary.Name,
                GlossaryId = glossary.GlossaryId,
                UserId = glossary.UserId,
                Password = glossary.Password
            };
            uof.GlossaryAccessRepository.getGlossaryAccessesByGlossaryId(id).ToList().ForEach(c =>
            {
                UserViewModel user = new UserViewModel
                {
                    UserId=c.UserId,
                    Name=c.User.Name,
                    Role=c.User.Role
                };
                gavm.GrantedUsers.Add(user);
            });
            return View(gavm);
        }



        [HttpGet]
        [Authorize(Roles = "teacher, admin")]
        public IActionResult Revoke(int GlossaryId,int UserId)
        {
            if (UserId == int.Parse(User.FindFirst(x => x.Type == "UserId").Value))
            {
                return NotFound();
            }
            GlossaryAccess ga = uof.GlossaryAccessRepository.getGlossaryAccessByGlossaryIdAndUserId(GlossaryId, UserId);
            if (ga == null)
                return NotFound();
            if (ga.Glossary.UserId!=ga.UserId)
            {
                return NotFound();
            }
            GlossaryRevokeViewModel gr = new GlossaryRevokeViewModel()
            {
                GlossaryId = ga.GlossaryId,
                GlossaryName = ga.Glossary.Name,
                UserEmail = ga.User.Email,
                UserId = ga.UserId,
                UserName = ga.User.Name
            };
            return View(gr);
        }
        [HttpPost]
        [Authorize(Roles = "teacher, admin")]
        public IActionResult Revoke(GlossaryRevokeViewModel glossaryRevoke)
        {
            if (glossaryRevoke.UserId==int.Parse(User.FindFirst(x => x.Type == "UserId").Value))
            {
                return NotFound();
            }
            if (glossaryRevoke != null)
            {
                int glossaryId = glossaryRevoke.GlossaryId;
                GlossaryAccess ga = uof.GlossaryAccessRepository.getGlossaryAccessByGlossaryIdAndUserId(glossaryRevoke.GlossaryId,glossaryRevoke.UserId);
                if (ga!=null)
                {
                    uof.GlossaryAccessRepository.Delete(ga);
                    uof.Save();
                    return Redirect("~/Glossary/Accesses/" + glossaryId);
                }
                else
                {
                    return View(glossaryRevoke);
                }
            }
            else
            {
                return View(glossaryRevoke);
            }
            
        }


        [HttpPost]
        [Authorize(Roles = "teacher, admin")]
        public IActionResult EditPassword(GlossaryAccessesViewModel glossaryAccess)
        {
            Glossary glossary= uof.GlossaryRepository.GetSingle(glossaryAccess.Glossary.GlossaryId);
            if (glossary == null )
            {
                return NotFound();
            }
            if (glossary.UserId != int.Parse(User.FindFirst(x => x.Type == "UserId").Value))
            {
                return NotFound();
            }
            glossary.Password = glossaryAccess.Glossary.Password;
            uof.GlossaryRepository.Edit(glossary);
            uof.Save();
            return Redirect("~/Glossary/Accesses/" + glossaryAccess.Glossary.GlossaryId);
        }

        [HttpPost]
        [Authorize(Roles = "teacher, admin")]
        public IActionResult SearchUsers(GlossaryAccessesViewModel glossaryAccess)
        {
            if (glossaryAccess.Glossary.UserId != int.Parse(User.FindFirst(x => x.Type == "UserId").Value))
            {
                return NotFound();
            }
            List<User> users = uof.UserRepository.GetAll().Where(x => x.Name.Contains(glossaryAccess.SearchedString)).ToList();
            glossaryAccess.SearchedUsers = new List<UserViewModel>();
            users.ForEach(c =>
            {
                UserViewModel user = new UserViewModel
                {
                    UserId = c.UserId,
                    Name = c.Name,
                    Role = c.Role
                };
                glossaryAccess.SearchedUsers.Add(user);
            });
            return Redirect("~/Glossary/Accesses/" + glossaryAccess.Glossary.GlossaryId);
        }

        [Authorize(Roles = "admin")]
        public IActionResult Details(int id)
        {
            Glossary glossary = uof.GlossaryRepository.GetSingle(id);
            if (glossary == null)
                return NotFound();
            return View(glossary);
        }


        [HttpGet]
        [Authorize(Roles = "student, teacher, admin")]
        public IActionResult View(int id)
        {
            Glossary glossary = uof.GlossaryRepository.GetSingle(id);
            if (glossary == null)
                return NotFound();


            GlossaryAccess ga = uof.GlossaryAccessRepository.getGlossaryAccessByGlossaryIdAndUserId(id,int.Parse(User.FindFirst(x => x.Type == "UserId").Value));
            if (ga == null)
            {
                return Redirect("~/Glossary/PasswordRequest/" + id);
            }

            GlossaryAndWordsViewModel gawvm = new GlossaryAndWordsViewModel
            {
                Glossary = new GlossaryListingViewModel()
            };
            gawvm.Glossary.GlossaryId = glossary.GlossaryId;
            gawvm.Glossary.Name = glossary.Name;
            gawvm.Glossary.CreatedAt = glossary.CreatedAt;
            gawvm.Glossary.Description = glossary.Description;
            gawvm.Glossary.UserName = glossary.User.Name;
            gawvm.Glossary.UserId = glossary.User.UserId;
            gawvm.Words = new List<WordViewModel>();
            uof.WordRepository.getWordsByGlossary(glossary.GlossaryId).ToList().ForEach(c =>
            {
                WordViewModel word = new WordViewModel
                {
                    WordId = c.WordId,
                    Term = c.Term,
                    CreatedAt=c.CreatedAt,
                    Definition = c.Definition,
                    UserId = c.User.UserId,
                    UserName = c.User.Name,
                    CourseId = c.Glossary.CourseId,
                    CourseName = c.Glossary.Course.Name
                };
                gawvm.Words.Add(word);
            });

            return View(gawvm);
        }
        [HttpGet]
        [Authorize(Roles = "student, teacher, admin")]
        public IActionResult PasswordRequest(int id)
        {
            Glossary glossary = uof.GlossaryRepository.GetSingle(id);
            if (glossary == null)
                return NotFound();
            GlossaryAccess ga = uof.GlossaryAccessRepository.getGlossaryAccessByGlossaryIdAndUserId(id, int.Parse(User.FindFirst(x => x.Type == "UserId").Value));
            if (ga != null)
            {
                return Redirect("~/Glossary/View/" + id);
            }
            PasswordRequestViewModel pr = new PasswordRequestViewModel
            {
                GlossaryId = glossary.GlossaryId,
                GlossaryName = glossary.Name
            };
            return View(pr);
        }
        [HttpPost]
        [Authorize(Roles = "student, teacher, admin")]
        public IActionResult PasswordRequest(PasswordRequestViewModel pr)
        {
            Glossary glossary = uof.GlossaryRepository.GetSingle(pr.GlossaryId);
            GlossaryAccess ga = uof.GlossaryAccessRepository.getGlossaryAccessByGlossaryIdAndUserId(glossary.GlossaryId,
                int.Parse(User.FindFirst(x => x.Type == "UserId").Value));
            if (ga!=null)
            {
                return Redirect("~/Glossary/View/" + pr.GlossaryId);
            }
            if (ModelState.IsValid)
            {
                if (pr.Password.Equals(glossary.Password))
                {
                    ga = new GlossaryAccess()
                    {
                        GlossaryId = glossary.GlossaryId,

StudentGlossary.WebMVC/Controllers/WordController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using StudentGlossary.Entities;
using StudentGlossary.Repositories;
using StudentGlossary.WebMVC.Models;

namespace StudentGlossary.WebMVC.Controllers
{
    public class WordController : Controller
    {
        IUnitOfWork uof;

        public WordController(IUnitOfWork uof)
        {
            this.uof = uof;
        }
        [Authorize(Roles = "admin")]
        public IActionResult Index()
        {
            List<Word> list = uof.WordRepository.GetAll().ToList();
            return View(list);
        }
        [Authorize(Roles = "admin")]
        public IActionResult Details(int id)
        {
            Word word = uof.WordRepository.GetSingle(id);
            if (word == null)
                return NotFound();
            return View(word);
        }

        [Authorize]
        public IActionResult View(int id)
        {
            Word word = uof.WordRepository.GetSingle(id);
            if (word == null)
            {
                return NotFound();
            }
            WordViewModel wvm = new WordViewModel
            {
                WordId=word.WordId,
                GlossaryId = word.GlossaryId,
                GlossaryName = word.Glossary.Name,
                Term =word.Term,
                UserName=word.User.Name,
                CreatedAt=word.CreatedAt,
                Definition=word.Definition,
                UserId = int.Parse(User.FindFirst(x => x.Type == "UserId").Value)
            };
            var userid = int.Parse(User.FindFirst(x => x.Type == "UserId").Value);
            if (wvm.UserId != userid && wvm.GlossaryUserId!= userid)
                return NotFound();
            return View(wvm);
        }

        [Authorize(Roles = "student, teacher, admin")]
        public IActionResult My()
        {
            List<WordViewModel> list = new List<WordViewModel>();
            uof.WordRepository.getWordsByUser(int.Parse(User.FindFirst(x => x.Type == "UserId").Value)).ToList().ForEach(c =>
            {
                WordViewModel word = new WordViewModel
                {
                    WordId = c.WordId,
                    Term = c.Term,
                    Definition = c.Definition,
                    CreatedAt = c.CreatedAt,
                    GlossaryId = c.GlossaryId,
                    GlossaryName = c.Glossary.Name,
                    UserId = c.UserId,
                    UserName = c.User.Name
                };
                list.Add(word);
            });

            return View(list);
        }
        [Authorize(Roles = "student, teacher, admin")]
        [HttpGet]
        public IActionResult Delete(int id)
        {
            Word word = uof.WordRepository.GetSingle(id);
            if (word == null)
                return NotFound();
            var userid = int.Parse(User.FindFirst(x => x.Type == "UserId").Value);
            if (word.UserId!= userid && word.Glossary.UserId!=userid)
                return NotFound();
            return View(word);
        }
        [Authorize(Roles = "student, teacher, admin")]
        [HttpPost]
        public IActionResult Delete(Word word)
        {
            var userid = int.Parse(User.FindFirst(x => x.Type == "UserId").Value);
            word = uof.WordRepository.GetSingle(word.WordId);
            if (word.UserId != userid && word.Glossary.UserId != userid)
                return NotFound();
            uof.WordRepository.Delete(word);
            uof.Save();
            return Redirect("~/Word/My/");
        }


        [Authorize(Roles = "student, teacher, admin")]
        [HttpGet]
        public IActionResult Edit(int id)
        {

            Word word = uof.WordRepository.GetSingle(id);
            if (word == null)
                return NotFound();
            var userid = int.Parse(User.FindFirst(x => x.Type == "UserId").Value);
            if (word.UserId != userid && word.Glossary.UserId != userid)
                return NotFound();
            WordViewModel wvm = new WordViewModel();

            wvm.WordId = word.WordId;
            wvm.Term = word.Term;
            wvm.Definition = word.Definition;
            wvm.UserId = word.User.UserId;
            wvm.UserName = word.User.Name;

            return View(wvm);
        }
        [Authorize(Roles = "student, teacher, admin")]
        [HttpPost]
        public IActionResult Edit(WordViewModel wordViewModel)
        {
            if (ModelState.IsValid)
            {
                Word word = uof.WordRepository.GetSingle(wordViewModel.WordId);
                var userid = int.Parse(User.FindFirst(x => x.Type == "UserId").Value);
                if (word.UserId != userid && word.Glossary.UserId != userid)
                    return NotFound();
                word.Term = wordViewModel.Term;
                word.Definition = wordViewModel.Definition;

                uof.WordRepository.Edit(word);
                uof.Save();
                return Redirect("~/Word/View/" + word.WordId);
            }
            else
            {
                return View(wordViewModel);
            }
        }
        [Authorize(Roles = "student, teacher, admin")]
        [HttpPost]
        public IActionResult Create(WordViewModel wvm)
        {

            if (ModelState.IsValid)
            {
                Word word = new Word()
                {
                    Term = wvm.Term,
                    Definition = wvm.Definition,
                    GlossaryId = wvm.GlossaryId,
                    UserId = int.Parse(User.FindFirst(x => x.Type == "UserId").Value)
                };
                var userid = int.Parse(User.FindFirst(x => x.Type == "UserId").Value);
                if (word.UserId != userid && word.Glossary.UserId != userid)
                    return NotFound();
                uof.WordRepository.Add(word);
                uof.Save();
                return Redirect("~/Word/View/" + word.WordId);
            }
            else
            {
                return View(wvm);
            }
        }
        [Authorize(Roles = "student, teacher, admin")]
        [HttpGet]
        public IActionResult Create(int id)
        {
            Glossary glossary = uof.GlossaryRepository.GetSingle(id);
            if (glossary==null)
            {
                return NotFound();
            }
            WordViewModel wvm = new WordViewModel
            {
                GlossaryId = glossary.GlossaryId,
                UserId = int.Parse(User.FindFirst(x => x.Type == "UserId").Value)
            };
            var userid = int.Parse(User.FindFirst(x => x.Type == "UserId").Value);
            if (wvm.UserId != userid && glossary.UserId != userid)
                return NotFound();
            return View(wvm);
        }
    }
}

StudentGlossary.WebMVC/Views/Word/Create.cshtml
@model WordViewModel
@{
    ViewData["Title"] = "Create Word";
}

<div class="panel panel-default">
    <div class="panel-heading"><h1>Word Creation</h1></div>
    <div class="panel-body">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <form asp-action="Create">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <input asp-for="GlossaryId" type="hidden" />
                    <input asp-for="UserId" type="hidden" />
                    <div class="form-group">
                        <label asp-for="Term" class="control-label"></label>
                        <input asp-for="Term" class="form-control" />
                        <span asp-validation-for="Term" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Definition" class="control-label"></label>
                        <textarea asp-for="Definition" rows="5" class="form-control"></textarea>
                        <span asp-validation-for="Definition" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <input type="submit" value="Create" class="btn btn-default" />
                    </div>
                </form>
            </div>
        </div>

    </div>
      <div class="panel-footer">
                <a asp-action="Index">Back to List</a>
            </div>
</div>

StudentGlossary.WebMVC/Views/Word/Delete.cshtml
@model StudentGlossary.Entities.Word
@{
    ViewData["Title"] = "Delete Word";
}
<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Word</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.WordId)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.WordId)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Term)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Term)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Definition)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Definition)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.UserId)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.UserId)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.GlossaryId)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.GlossaryId)
        </dd>
    </dl>

    <form asp-action="Delete">
        <input asp-for="WordId" type="hidden" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

StudentGlossary.WebMVC/Views/Word/Details.cshtml
@model StudentGlossary.Entities.Word

<div>
    <h4>Word</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.WordId)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.WordId)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Term)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Term)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Definition)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Definition)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.UserId)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.UserId)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.GlossaryId)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.GlossaryId)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new {  id = Model.WordId  }) |
    <a asp-action="Index">Back to List</a>
</div>

StudentGlossary.WebMVC/Views/Word/Edit.cshtml
@model WordViewModel
@{
    ViewData["Title"] = "Edit Word";
}
<h4>Word</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input asp-for="WordId" type="hidden" />
            <div class="form-group">
                <label asp-for="Term" class="control-label"></label>
                <input asp-for="Term" class="form-control" />
                <span asp-validation-for="Term" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Definition" class="control-label"></label>
                <textarea asp-for="Definition" class="form-control" rows="5"></textarea>
                <span asp-validation-for="Definition" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

StudentGlossary.WebMVC/Views/Word/Index.cshtml
@model IEnumerable<StudentGlossary.Entities.Word>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
                <th>
                    @Html.DisplayNameFor(model => model.WordId)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Term)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Definition)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.UserId)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.GlossaryId)
                </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.WordId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Term)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Definition)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.UserId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.GlossaryId)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new {  id=item.WordId  }) |
                @Html.ActionLink("Details", "Details", new {  id=item.WordId }) |
                @Html.ActionLink("Delete", "Delete", new {  id=item.WordId })
            </td>
        </tr>
}
    </tbody>
</table>

StudentGlossary.WebMVC/Views/Word/My.cshtml
@model List<WordViewModel>
    @{
        ViewData["Title"] = "My words";
    }
    <div class="container">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h1>My (@User.FindFirst(x => x.Type == "Name").Value) Words</h1>
            </div>
            <div class="panel-body">
                <div class="row">
                    @if (!Model.Any())
                    {
                        <h2 style="text-align:center">... You dont have any words!</h2>
                    }
                    else
                    {
                        @foreach (var item in Model)
                        {
                            <div class="col-md-10 col-md-offset-1">
                                <div class="panel-group">
                                    <div class="panel panel-default">
                                        <div class="panel-heading">
                                            @Html.DisplayFor(modelItem => item.Term)
                                            <div class="pull-right">
                                                @Html.ActionLink(item.GlossaryName, "View","Glossary", new { id = item.GlossaryId })
                                               
                                            </div>
                                        </div>
                                        <div class="panel-body"><b>@Html.DisplayFor(modelItem => item.Term)</b> - @Html.DisplayFor(modelItem => item.Definition)</div>
                                        <div class="panel-footer">
                                            @Html.DisplayFor(modelItem => item.CreatedAt)
                                            <div class="pull-right">
                                                @Html.ActionLink("View", "View", new { id = item.WordId }) |
                                                @Html.ActionLink("Edit", "Edit", new { id = item.WordId }) |
                                                @Html.ActionLink("Delete", "Delete", new { id = item.WordId })
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        }
                    }
                </div>
            </div>
        </div>
    </div>

StudentGlossary.WebMVC/Views/Word/View.cshtml
@model WordViewModel
@{
    ViewData["Title"] = "Word View";
}

<div class="panel panel-default">
    <div class="panel-heading">
        <h2>@Model.Term</h2>
        <div class="pull-right">
            @Model.UserName, at @Model.CreatedAt
        </div>
    </div>
    <div class="panel-body">
        <b>@Model.Term</b>
        -
        @Model.Definition
    </div>
    <div class="panel-footer">
        @Html.ActionLink(Model.GlossaryName, "View", "Glossary", new { id = Model.GlossaryId })
        <div class="pull-right">
            @Html.ActionLink("Edit", "Edit", "Word", new { id = Model.WordId }) |
            @Html.ActionLink("View", "View", "Word", new { id = Model.WordId }) |
            @Html.ActionLink("Delete", "Delete", "Word", new { id = Model.WordId })
        </div>
    </div>
</div>