StudentGlossary.WebMVC/Controllers/CourseController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using StudentGlossary.Entities;
using StudentGlossary.Repositories;

namespace StudentGlossary.WebMVC.Controllers
{
    public class CourseController : Controller
    {
        IUnitOfWork uof;
        public CourseController(IUnitOfWork uof)
        {
            this.uof = uof;
        }
        [Authorize(Roles = "admin")]
        public IActionResult Index()
        {
            List<Course> list = uof.CourseRepository.GetAll().ToList();
            return View(list);
        }

        [Authorize(Roles = "admin")]
        [HttpGet]
        public IActionResult Delete(string id)
        {
            Course course = uof.CourseRepository.GetSingle(id);
            if (course == null)
                return NotFound();
            return View(course);
        }
        [Authorize(Roles = "admin")]
        [HttpPost]
        public IActionResult Delete(string id, IFormCollection form)
        {
            Course course = uof.CourseRepository.GetSingle(id);
            if (course != null)
            {
                uof.CourseRepository.Delete(course);
            }
            return RedirectToAction("Index");
        }

        [Authorize(Roles = "admin")]
        [HttpGet]
        public IActionResult Edit(string id)
        {
            Course course = uof.CourseRepository.GetSingle(id);
            if (course == null)
                return NotFound();
            return View(course);
        }
        [Authorize(Roles = "admin")]
        [HttpPost]
        public IActionResult Edit(Course course)
        {
            uof.CourseRepository.Edit(course);
            return RedirectToAction("Index");
        }
        [Authorize(Roles = "admin")]
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }
        [Authorize(Roles = "admin")]
        [HttpPost]
        public IActionResult Create(Course course)
        {
            uof.CourseRepository.Add(course);
            uof.Save();
            return RedirectToAction("Index");
        }
    }
}

StudentGlossary.WebMVC/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using StudentGlossary.Entities;
using StudentGlossary.Repositories;

namespace StudentGlossary.WebMVC.Controllers
{
    public class UserController : Controller
    {
        IUnitOfWork uof;

        public UserController(IUnitOfWork uof)
        {
            this.uof = uof;
        }



        [Authorize(Roles = "admin")]
        public IActionResult Index()
        {
            List<User> list = uof.UserRepository.GetAll().ToList();
            return View(list);
        }



        [Authorize(Roles = "admin")]
        public IActionResult Details(int id)
        {
            User user = uof.UserRepository.GetSingle(id);
            if (user == null)
                return NotFound();
            return View(user);
        }



        [Authorize(Roles = "admin")]
        [HttpGet]
        public IActionResult Delete(int id)
        {
            User user = uof.UserRepository.GetSingle(id);
            if (user == null)
                return NotFound();
            return View(user);
        }

        [Authorize(Roles = "admin")]
        [HttpPost]
        public IActionResult Delete(User user)
        {
            uof.UserRepository.Delete(user);
            uof.Save();
            return View();
        }



        [Authorize(Roles = "admin")]
        [HttpGet]
        public IActionResult Edit(int id)
        {
            User user = uof.UserRepository.GetSingle(id);
            if (user == null)
                return NotFound();
            return View(user);
        }

        [Authorize(Roles = "admin")]
        [HttpPost]
        public IActionResult Edit(User user)
        {
            uof.UserRepository.Edit(user);
            uof.Save();
            return RedirectToAction("Index");
        }



        [Authorize(Roles = "admin")]
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [Authorize(Roles = "admin")]
        [HttpPost]
        public IActionResult Create(User user)
        {
            uof.UserRepository.Add(user);
            uof.Save();
            return RedirectToAction("Index");
        }
    }
}

StudentGlossary.WebMVC/Controllers/WordController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using StudentGlossary.Entities;
using StudentGlossary.Repositories;
using StudentGlossary.WebMVC.Models;

namespace StudentGlossary.WebMVC.Controllers
{
    public class WordController : Controller
    {
        IUnitOfWork uof;

        public WordController(IUnitOfWork uof)
        {
            this.uof = uof;
        }
        [Authorize(Roles = "admin")]
        public IActionResult Index()
        {
            List<Word> list = uof.WordRepository.GetAll().ToList();
            return View(list);
        }
        [Authorize(Roles = "admin")]
        public IActionResult Details(int id)
        {
            Word word = uof.WordRepository.GetSingle(id);
            if (word == null)
                return NotFound();
            return View(word);
        }

        [Authorize]
        public IActionResult View(int id)
        {
            Word word = uof.WordRepository.GetSingle(id);
            if (word == null)
            {
                return NotFound();
            }
            WordViewModel wvm = new WordViewModel
            {
                WordId=word.WordId,
                GlossaryId = word.GlossaryId,
                GlossaryName = word.Glossary.Name,
                Term =word.Term,
                UserName=word.User.Name,
                CreatedAt=word.CreatedAt,
                Definition=word.Definition,
                UserId = int.Parse(User.FindFirst(x => x.Type == "UserId").Value)
            };
            var userid = int.Parse(User.FindFirst(x => x.Type == "UserId").Value);
            if (wvm.UserId != userid && wvm.GlossaryUserId!= userid)
                return NotFound();
            return View(wvm);
        }

        [Authorize(Roles = "student, teacher, admin")]
        public IActionResult My()
        {
            List<WordViewModel> list = new List<WordViewModel>();
            uof.WordRepository.getWordsByUser(int.Parse(User.FindFirst(x => x.Type == "UserId").Value)).ToList().ForEach(c =>
            {
                WordViewModel word = new WordViewModel
                {
                    WordId = c.WordId,
                    Term = c.Term,
                    Definition = c.Definition,
                    CreatedAt = c.CreatedAt,
                    GlossaryId = c.GlossaryId,
                    GlossaryName = c.Glossary.Name,
                    UserId = c.UserId,
                    UserName = c.User.Name
                };
                list.Add(word);
            });

            return View(list);
        }
        [Authorize(Roles = "student, teacher, admin")]
        [HttpGet]
        public IActionResult Delete(int id)
        {
            Word word = uof.WordRepository.GetSingle(id);
            if (word == null)
                return NotFound();
            var userid = int.Parse(User.FindFirst(x => x.Type == "UserId").Value);
            if (word.UserId!= userid && word.Glossary.UserId!=userid)
                return NotFound();
            return View(word);
        }
        [Authorize(Roles = "student, teacher, admin")]
        [HttpPost]
        public IActionResult Delete(Word word)
        {
            var userid = int.Parse(User.FindFirst(x => x.Type == "UserId").Value);
            word = uof.WordRepository.GetSingle(word.WordId);
            if (word.UserId != userid && word.Glossary.UserId != userid)
                return NotFound();
            uof.WordRepository.Delete(word);
            uof.Save();
            return Redirect("~/Word/My/");
        }


        [Authorize(Roles = "student, teacher, admin")]
        [HttpGet]
        public IActionResult Edit(int id)
        {

            Word word = uof.WordRepository.GetSingle(id);
            if (word == null)
                return NotFound();
            var userid = int.Parse(User.FindFirst(x => x.Type == "UserId").Value);
            if (word.UserId != userid && word.Glossary.UserId != userid)
                return NotFound();
            WordViewModel wvm = new WordViewModel();

            wvm.WordId = word.WordId;
            wvm.Term = word.Term;
            wvm.Definition = word.Definition;
            wvm.UserId = word.User.UserId;
            wvm.UserName = word.User.Name;

            return View(wvm);
        }
        [Authorize(Roles = "student, teacher, admin")]
        [HttpPost]
        public IActionResult Edit(WordViewModel wordViewModel)
        {
            if (ModelState.IsValid)
            {
                Word word = uof.WordRepository.GetSingle(wordViewModel.WordId);
                var userid = int.Parse(User.FindFirst(x => x.Type == "UserId").Value);
                if (word.UserId != userid && word.Glossary.UserId != userid)
                    return NotFound();
                word.Term = wordViewModel.Term;
                word.Definition = wordViewModel.Definition;

                uof.WordRepository.Edit(word);
                uof.Save();
                return Redirect("~/Word/View/" + word.WordId);
            }
            else
            {
                return View(wordViewModel);
            }
        }
        [Authorize(Roles = "student, teacher, admin")]
        [HttpPost]
        public IActionResult Create(WordViewModel wvm)
        {

            if (ModelState.IsValid)
            {
                Word word = new Word()
                {
                    Term = wvm.Term,
                    Definition = wvm.Definition,
                    GlossaryId = wvm.GlossaryId,
                    UserId = int.Parse(User.FindFirst(x => x.Type == "UserId").Value)
                };
                var userid = int.Parse(User.FindFirst(x => x.Type == "UserId").Value);
                if (word.UserId != userid && word.Glossary.UserId != userid)
                    return NotFound();
                uof.WordRepository.Add(word);
                uof.Save();
                return Redirect("~/Word/View/" + word.WordId);
            }
            else
            {
                return View(wvm);
            }
        }
        [Authorize(Roles = "student, teacher, admin")]
        [HttpGet]
        public IActionResult Create(int id)
        {
            Glossary glossary = uof.GlossaryRepository.GetSingle(id);
            if (glossary==null)
            {
                return NotFound();
            }
            WordViewModel wvm = new WordViewModel
            {
                GlossaryId = glossary.GlossaryId,
                UserId = int.Parse(User.FindFirst(x => x.Type == "UserId").Value)
            };
            var userid = int.Parse(User.FindFirst(x => x.Type == "UserId").Value);
            if (wvm.UserId != userid && glossary.UserId != userid)
                return NotFound();
            return View(wvm);
        }
    }
}

StudentGlossary.WebMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - StudentGlossary</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/custom_theme.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">StudentGlossary</a>
            </div>
            <div class="navbar-collapse collapse">
                @await Html.PartialAsync("_NavbarPartial")
                @await Html.PartialAsync("_LoginPartial")
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - Andrei Gavrilov, Janar Tomband</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

StudentGlossary.WebMVC/Views/Shared/_NavbarPartial.cshtml
<ul class="nav navbar-nav">
    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>

    @if (User.IsInRole("teacher"))
    {
        <li><a asp-area="" asp-controller="Word" asp-action="My">My Words</a></li>
        <li><a asp-area="" asp-controller="Glossary" asp-action="My">My Glossaries</a></li>
        <li><a asp-area="" asp-controller="Glossary" asp-action="Granted">Granted Glossaries</a></li>
        <li><a asp-area="" asp-controller="Glossary" asp-action="Glossaries">Glossaries</a></li>
    }
    @if (User.IsInRole("student"))
    {
        <li><a asp-area="" asp-controller="Word" asp-action="My">My Words</a></li>
        <li><a asp-area="" asp-controller="Glossary" asp-action="Granted">Granted Glossaries</a></li>
        <li><a asp-area="" asp-controller="Glossary" asp-action="Glossaries">Glossaries</a></li>
    }
    @if (User.IsInRole("admin"))
    {
        <li><a asp-area="" asp-controller="Word" asp-action="My">My Words</a></li>
        <li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                Glossaries
                <span class="caret"></span>
            </a>
            <ul class="dropdown-menu">
                <li><a asp-area="" asp-controller="Glossary" asp-action="My">My Glossaries</a></li>
                <li><a asp-area="" asp-controller="Glossary" asp-action="Granted">Granted Glossaries</a></li>
                <li><a asp-area="" asp-controller="Glossary" asp-action="Glossaries">Glossaries</a></li>
            </ul>
        </li>
        <li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                Admin Panel
                <span class="caret"></span>
            </a>
            <ul class="dropdown-menu">
                <li><a asp-area="" asp-controller="User" asp-action="Index">A-Users</a></li>
                <li><a asp-area="" asp-controller="Course" asp-action="Index">A-Courses</a></li>
            </ul>
        </li>
    }
    <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
</ul>